name: 'Create Git Tag'
description: 'Creates a Git tag with version info'
inputs:
  kernel_ver:
    description: 'Kernel version (e.g., 6.6.127)'
    required: true
  tag_ver:
    description: 'Additional tag version'
    required: true
  ksu_ver:
    description: 'KernelSU version (e.g., ksu_v3.0.0_sha)'
    required: true
  gh_token:
    description: 'Github Token'
    required: true
outputs:
  git_tag:
    description: 'Final Git Tag'
    value: ${{ steps.tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Set Git Remote URL
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        USERNAME: ${{ github.repository_owner }}
        REPO: ${{ github.repository }}
      run: |
        git remote set-url origin https://$USERNAME:$GITHUB_TOKEN@github.com/$REPO.git
      shell: bash

    - name: Generate Tag
      id: tag
      env:
        KERN_VER: ${{ inputs.kernel_ver }}
        TAG_VER: ${{ inputs.tag_ver }}
        KSU_VER: ${{ inputs.ksu_ver }}
      run: |
        FINAL_TAG="$KERN_VER-android15-8-$TAG_VER-4k@$KSU_VER"
        echo "tag=$FINAL_TAG" >> $GITHUB_OUTPUT
        echo "Generated tag: $FINAL_TAG"
      shell: bash

    - name: Create and Push Tag
      run: |
        git tag -a "${{ steps.tag.outputs.tag }}" -m "${{ steps.tag.outputs.tag }}" ${GITHUB_SHA}
        git push origin ${{ steps.tag.outputs.tag }}
      shell: bash
