name: Manual Kernel Build

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Build environment'
        required: true
        type: choice
        options:
          - GitHub Runner
          - Self-Hosted
        default: GitHub Runner
      kernel:
        description: 'Kernel to build'
        required: true
        type: choice
        options:
          - Stock Kernel
          - KernelSU
          - KernelSU-Next
          - SukiSU
          - ReSukiSU
        default: ReSukiSU
      susfs:
        description: 'Patch for SUSFS'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ${{ inputs.runner == 'Self-Hosted' && 'self-hosted' || 'ubuntu-latest' }}

    steps:
      - name: Maximize Github Runner Space
        if: ${{ inputs.runner == 'GitHub Runner' }}
        uses: justinthelaw/maximize-github-runner-space@v0.9.0
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync git build-essential bc bison flex libssl-dev libelf-dev python3 python3-pip curl zip unzip
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Sync kernel and build env
        env:
          GIT_REPO: '${{ github.server_url }}/${{ github.repository }}.git'
        run: |
          echo "Building kernel: ${{ inputs.kernel }}"
          echo "SUSFS: ${{ inputs.susfs }}"
          echo "Using manifest from: $GIT_REPO"
          export PATH="$HOME/bin:$PATH"

          mkdir nt_kernel_build
          cd nt_kernel_build

          repo init --depth=1 -u $GIT_REPO < /dev/null
          stdbuf -oL -eL repo sync -j$(nproc) -v --fail-fast 2>&1

      - name: Build Kernel
        working-directory: nt_kernel_build
        id: build
        env:
          SELECTED_KERNEL: ${{ inputs.kernel }}
          SUSFS: ${{ inputs.susfs }}
        run: |
          echo "Building kernel..."

          echo "kernel_ver=$(make -C common kernelversion)" >> $GITHUB_OUTPUT
          echo "tag_ver=g$(git -C common rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          
          if [ "$SELECTED_KERNEL" = "KernelSU-Next" ]; then
              KSU_DIR="common/KernelSU-Next"
          else
              KSU_DIR="common/KernelSU"
          fi

          if [ "$SELECTED_KERNEL" = "Stock Kernel" ]; then
              echo "ksu_ver=Stock" >> $GITHUB_OUTPUT
          else
              echo "ksu_ver=$SELECTED_KERNEL-$(git -C "$KSU_DIR" rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi

          KERNEL="kernel"
          if [ "$SELECTED_KERNEL" = "Stock Kernel" ] && [ "$SUSFS" = true ]; then
              echo "No SUSFS option for Stock Kernel"
              echo "Using Normal Stock Kernel"
          fi

          if [ "$SELECTED_KERNEL" = "KernelSU" ]; then
              KERNEL="${KERNEL}_ksu"
          fi
          if [ "$SELECTED_KERNEL" = "KernelSU-Next" ]; then
              KERNEL="${KERNEL}_ksun"
          fi
          if [ "$SELECTED_KERNEL" = "SukiSU" ]; then
              KERNEL="${KERNEL}_sukisu"
          fi
          if [ "$SELECTED_KERNEL" = "ReSukiSU" ]; then
              KERNEL="${KERNEL}_resukisu"
          fi

          if [ "$SUSFS" = true ]; then
              if [ "$SELECTED_KERNEL" = "Stock Kernel" ]; then
                  echo "No SUSFS option for Stock Kernel"
                  echo "Using Normal Stock Kernel"
              else
                  KERNEL="${KERNEL}_susfs"
              fi
          fi

          tools/bazel run --config=stamp //froggerpro:$KERNEL

      - name: Upload Kernel Modules
        uses: actions/upload-artifact@v7
        with:
          name: kernel-modules-${{ github.sha }}
          path: nt_kernel_build/out/msm-kernel-sun-perf/dist/*.ko
          compression-level: 9
          archive: true

      - name: Upload Boot Image
        uses: actions/upload-artifact@v7
        with:
          name: boot-img-${{ github.sha }}
          path: nt_kernel_build/out/msm-kernel-sun-perf/dist/boot.img
          archive: false

      - name: Create git tag
        uses: ./.github/actions/create_tag
        id: tag
        with:
          kernel_ver: ${{ steps.build.outputs.kernel_ver }}
          tag_ver: ${{ steps.build.outputs.tag_ver }}
          ksu_ver: ${{ steps.build.outputs.ksu_ver }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog
        run: |
          echo "# Kernel Build for froggerPro (Nothing Phone (4a) Pro)" > ${{ github.workspace }}/CHANGELOG.txt
          echo "" >> ${{ github.workspace }}/CHANGELOG.txt
          echo "Kernel Version: ${{ steps.build.outputs.kernel_ver }}-${{ steps.build.outputs.tag_ver }}" >> ${{ github.workspace }}/CHANGELOG.txt
          echo "Kernel Type: ${{ inputs.kernel }}" >> ${{ github.workspace }}/CHANGELOG.txt
          echo "SUSFS: ${{ inputs.susfs }}" >> ${{ github.workspace }}/CHANGELOG.txt
          echo "Runner: ${{ inputs.runner }}" >> ${{ github.workspace }}/CHANGELOG.txt

      - name: Create Github Release
        uses: ./.github/actions/create_release
        with:
          tag_name: ${{ steps.tag.outputs.git_tag }}
          release_name: ${{ steps.build.outputs.kernel_ver }}-${{ steps.build.outputs.tag_ver }}-${{ steps.build.outputs.ksu_ver }}
          body_path: ${{ github.workspace }}/CHANGELOG.txt
          files: "nt_kernel_build/out/msm-kernel-sun-perf/dist/boot.img"
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove everything
        run: |
          rm -rf nt_kernel_build


